name: spull
description: "Spull — a pixel-art media downloader."
publish_to: 'none'
version: 1.2.6+1
environment:
  sdk: ^3.13.2

dependencies:
  archive: ^4.0.7
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/spull_logo.svg
